name: ❓ Support
description: "If you need help using Bogus 🏥"
labels: ["question"]
body:

  - type: markdown
    attributes:
      value: |
        ## Version Information

  - type: input
    id: version-bogus
    attributes:
      label: Bogus NuGet Package
      description: What version of Bogus are you using?
      placeholder: ex. v35.0.1
    validations:
      required: true

  - type: input
    id: version-dotnet
    attributes:
      label: .NET Version
      description: What version of .NET are using?
      placeholder: ex. Full Framework 4.7.1 or .NET 8?
    validations:
      required: true

  - type: input
    id: version-visualstudio
    attributes:
      label: Visual Studio Version
      description: What version of Visual Studio are using?
      placeholder: ex. 17.8?
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Windows
        - Linux
        - MacOS
        - Other
    validations:
        required: true

  - type: markdown
    attributes:
      value: |
        ## Support Issue

  - type: input
    id: bogus-locale
    attributes:
      label: What locale are you using with Bogus?
      description: 
      placeholder: ex. en_GB
    validations:
      required: true

  - type: textarea
    id: support-request
    attributes:
      label: What's the problem?
      description: Please describe the support issue.
      placeholder: 
    validations:
      required: true

  - type: textarea
    id: support-linqpad
    attributes:
      label: Provide LINQPad Example
      description: |
        Please provide a LINQPad example of what you are trying to do. LINQPad can be downloaded here: https://www.linqpad.net/.
      placeholder: "LINQPad can be downloaded here: https://www.linqpad.net/"
    validations:
      required: true

  - type: textarea
    id: support-alternatives
    attributes:
      label: What other possible solutions or alternatives have you considered?
      description: Are there any workarounds or alternatives?
      placeholder: 
    validations:
      required: true